name: CI Pipeline

on:
  push:
    branches: [ master ] # Assuming 'master', adjust if needed
  pull_request:
    branches: [ master ] # Assuming 'master', adjust if needed

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Updated to v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5 # Updated to v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhidapi-hidraw0

    - name: Install Python dependencies (pip, tox)
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions # Using tox-gh-actions for better integration

    - name: Run linters (flake8)
      run: |
        tox -e flake8

    - name: Run tests with tox
      run: tox
